### ISSUE TITLE
Issue with Latest wiredep version

### ISSUE THREAD

**Issue by sebastianchacko89** [sagrawal14/bootstrap-angular-validation#27] opened 2017-02-20 22:16 UTC
Hi Team,

First Off, great library. Thanks for creating this!!

But recently i have been seeing some console errors and the validation not working properly after updating to the latest version of grunt-wiredep(3.0.1). The console error looks like:

    TypeError: a.parents is not a function
        at Object.isValidationDisabled 

    at dist/bootstrap-angular-validation-all.min.js:1:9087)

As per the latest wiredep changelog, the breaking changes are:
REMOVED: Auto-detecting paths outside of a  block.

Previously, if your source file included a reference to one of your Bower dependencies outside of your  block, wiredep wouldn't inject it inside of the block. This was originally done to support using Modernizr.js in the <head> section of your HTML file without it being re-injected in the <body>. Not only is this no longer Modernizr's recommended practice, but we have since added the exclude option in wiredep's configuration that would allow you to duplicate this behavior without any magic.

REMOVED: Elite dependencies.

Previously, wiredep kept a list of packages that were known to be required before any other scripts. This included jQuery, es5-shim, etc. This was originally done in the very early days of Bower, as packages weren't properly listing their dependencies (if they even had a bower.json at all!). Things have come a long way since then, and this should no longer be required. If you are using packages that don't list their dependencies properly, offer them a PR with the correction.

https://github.com/taptapship/wiredep/releases

Could either of these be the issue??

Thanks,
Sebastian

**Comment by sagrawal31** [comment] 2017-02-26 12:08
Thanks for raising an issue @sebastianchacko89! I don't think that the error you are getting is any related to `wiredep`. May I know the version of this library you are using and how you are including the JS files?

**Comment by sebastianchacko89** [comment] 2017-02-26 21:34
@sagrawal14  Thanks for looking into this so soon!
I am using version 1.0.5 of this library. I am using bower to insert the dependencies.
The issue happened when I updated wiredep to ^3.0.1. I was using ^2.0.0 before. I reverted it back to ^2.0.0 and all is good now. 
Is there something I'm missing?
Thanks again for your time!

**Comment by sebastianchacko89** [comment] 2017-04-28 18:18
hey @sagrawal31 Any chance you had time to take a look at this? 

Thanks in advance for your help!! :)

**Comment by sagrawal31** [comment] 2017-04-29 04:09
@sebastianchacko89 I'll take a look at it again today. Thanks for the ping.

**Comment by sagrawal31** [comment] 2017-04-30 07:41
If you are using [`grunt-wiredep`](https://github.com/stephenplusplus/grunt-wiredep)

**Comment by sagrawal31** [comment] 2017-04-30 10:56
Hi @sebastianchacko89 I was sure about the problem when I read again the description yesterday but I wanted to be sure with an example and a fix to this issue. You were right, it's because of the removal of the elite dependencies from the `wiredep` in [wiredep@v3.0.0](https://github.com/taptapship/wiredep/releases/tag/v3.0.0).

Basically, this library was developed to be used without the requirement of jQuery but if your app uses jQuery then the jQuery MUST be added before angular to use the methods from jQuery itself instead of jqLite. This library checks if jQuery is included or not here at [utils.js](https://github.com/sagrawal31/bootstrap-angular-validation/blob/v1.0.7/src/utils.js) and if that is not available then only we implement the required methods otherwise uses it from jQuery itself (since jQuery is GREAT at element lookup)

I created a [sample app](https://github.com/sagrawal31/test-wiredep/commits/master) to reproduce this issue and a solution. 

Let's look at the commits one by one.

1. In the 1st commit, I simply created the app with `yo-man angular` and running `grunt serve` (having older version of wiredep) causes the jQuery to be installed first in `index.html`
2. In the 2nd commit https://github.com/sagrawal31/test-wiredep/commit/dbbb5f9925caec65cf8e5a861b2f6c2288e69fda, I added this library via bower with and a test form and the validation was working
3. In the 3rd commit https://github.com/sagrawal31/test-wiredep/commit/755559d41f7a0527d7aff47b3482e903cec72156 I upgraded the wiredep, which installed angular before jquery (in `index.html`) due to removal of elite dependency hence this issue
4. To fix this issue, we need to tell wiredep that `jquery` is a dependency (not really) of `angular` so we needs to make a small change in the `bower.json` that I have made in the 4th commit https://github.com/sagrawal31/test-wiredep/commit/313f9cfc1f8f0d568effdbc640923a2c2fe8bdc3

Conclusion: So finally fix this issue, modify your `bower.json` file and add the following under the `"overrides"` block:

```json
"angular": {
  "dependencies": {
    "jquery": "3.2.1"
  }
}
```

(whatever version of jQuery you are using)

So this error isn't really related to this library or angular because both angular & this library can work without jQuery. But if jQuery added there is some extra work is getting added which I will try to fix in future.

Thanks again for using this library and your patience. :)

**Comment by sagrawal31** [comment] 2017-04-30 11:00
I'm closing this issue as of now and will work around for sure in future. Feel free to reopen 😄

**Closed as completed by sagrawal31** 2017-04-30 11:00 UTC
Labels: wontfix, needs investigation

**Comment by sebastianchacko89** [comment] 2017-05-01 19:13
Wow. Thanks @sagrawal31 for the great explanation. I can tell it took a good amount of analysis for you to come up with the solution.
I just tried it out and it looks good. 
Thanks again for taking the time to analyze this. Appreciate your commitment! :)
